---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/temporal.yaml
    kompose.version: 1.26.1 (1b040dd2)
  labels:
    io.kompose.service: temporal-ui
  name: temporal-ui
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: temporal-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/temporal.yaml
    kompose.version: 1.26.1 (1b040dd2)
  labels:
    io.kompose.service: temporal-ui
  name: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: temporal-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/temporal.yaml
        kompose.version: 1.26.1 (1b040dd2)
      labels:
        io.kompose.network/temporal-network: "true"
        io.kompose.service: temporal-ui
    spec:
      containers:
        - env:
            - name: TEMPORAL_ADDRESS
              value: temporal:7233
            - name: TEMPORAL_CORS_ORIGINS
              value: http://localhost:3000
            - name: TEMPORAL_TLS_CA
              value: /etc/temporal/config/certs/ca.cert
            - name: TEMPORAL_TLS_CERT
              value: /etc/temporal/config/certs/cluster.cert
            - name: TEMPORAL_TLS_KEY
              value: /etc/temporal/config/certs/cluster.key
            - name: TEMPORAL_TLS_ENABLE_HOST_VERIFICATION
              value: "true"
            - name: TEMPORAL_TLS_SERVER_NAME
              value: tls-sample
          image: temporalio/ui:2.2.3
          name: temporal-ui
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: mtls-certs
              mountPath: /etc/temporal/config/certs
              readOnly: true
      restartPolicy: Always
      enableServiceLinks: false
      volumes:
        - name: mtls-certs
          projected:
            sources:
              - secret:
                  name: ca-cert
              - secret:
                  name: cluster-cert
status: {}